projects:
  chatAppAPI:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: i2s6pbdirzf7nixnfrbbly76x4
      endpoints:
        prod: >-
          https://ijaoxj6nmzhkddo7xgpiion4oe.appsync-api.us-west-2.amazonaws.com/graphql
